# Generated by Django 5.0.7 on 2024-08-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
                ('like', models.BigIntegerField(default=0)),
                ('view', models.BigIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
