# Generated by Django 5.0.7 on 2024-08-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTable',
            new_name='tbl_proj',
        ),
    ]
